# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: ubuntu-latest

# pipelines>Stages>Jobs >Task(Steps)
jobs:
- job:Job1
steps:  
    - script:echo Add task1
      displayName:'RUn Taskl1 display'

    - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- job:Job2
steps:
      - script:echo Add task2
        displayName:'RUn Task2 display'
