# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest



# Pipelines > Stages > Jobs > Task(steps)
stages:
  - stage: BuildsApp 
    displayName: 'Run a one-line script'
    jobs:
    - job: Job1
      dependsOn: Job2
      steps:
      - script: echo Job1, world!
      displayName: Run a one-line script

    - job: Job2
      steps:
      - script: "
      echo job2, world!
      echo job21, world!"
      displayName: Run a one-line script

  - stage: DEVBUILD
    displayName: 'Run a one-line script'
    jobs:
    - job: Job21
      steps:
      - script: echo Job1, world!
      displayName: Run a one-line script

    - job: Job22
      steps:
      - script: "
      echo job21, world!
      echo job23, world!"
      displayName: Run a one-line script
      

  - stage: PRODBUILD
    displayName: 'Run a one-line script'
    dependsOn: 
    - BuildsApp    
    - DEVBUILD    
    jobs:
    - job: Job21
      steps:
      - script: echo Job1, world!
      displayName: Run a one-line script

    - job: Job22
      steps:
      - script: "
      echo job21, world!
      echo job23, world!"
      displayName: Run a one-line script