# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: ubuntu-latest

# pipelines>Stages>Jobs >Task(Steps)
jobs:
-job:job1
steps:
-script:
  echo Add task1
  displayName:'RUn Taskl1 display'

  -job:job2
steps:
-script:
  echo Add task2
  displayName:'RUn Task2 display'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
